
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <..\Janus.h>




#include <rpygen/janus__XmlElementDefinition.hpp>

namespace rpygen {

using namespace janus;


template <typename CfgBase>
using PyTrampolineCfgBase_janus__Janus =
    PyTrampolineCfg_janus__XmlElementDefinition<
CfgBase
>;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_janus__Janus :
    PyTrampolineCfgBase_janus__Janus< CfgBase>
{
    using Base = janus::Janus;

    using override_base_clear_v = janus::Janus;
    using override_base_setXmlFileName_KRTaFileString_KRTaFileString = janus::Janus;
    using override_base_setXmlFileName_KRTaFileString_KRTaFileString_KRTaFileString = janus::Janus;
    using override_base_setXmlFileBuffer_Ph_KRTsize_t = janus::Janus;
    using override_base_exportToFile_KRTaFileString = janus::Janus;
    using override_base_exportToBuffer_RTostringstream = janus::Janus;
    using override_base_exportToBuffer_RPh = janus::Janus;
    using override_base_exportToDocumentObjectModel_KRTaString = janus::Janus;
    using override_base_parseDOM_v = janus::Janus;
    using override_base_initialiseDependencies_v = janus::Janus;
};


template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_janus__Janus =
    PyTrampoline_janus__XmlElementDefinition<
        PyTrampolineBase
        
        , PyTrampolineCfg
    >
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_janus__Janus : PyTrampolineBase_janus__Janus<PyTrampolineBase, PyTrampolineCfg> {
    using PyTrampolineBase_janus__Janus<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_janus__Janus;



#ifndef RPYGEN_DISABLE_clear_v
    void clear() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_clear_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "clear", );
        return CxxCallBase::clear();
    }
#endif

#ifndef RPYGEN_DISABLE_setXmlFileName_KRTaFileString_KRTaFileString
    void setXmlFileName(const dstoute::aFileString& documentName, const dstoute::aFileString& keyFileName) override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_setXmlFileName_KRTaFileString_KRTaFileString;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "setXmlFileName", documentName, keyFileName);
        return CxxCallBase::setXmlFileName(documentName, keyFileName);
    }
#endif

#ifndef RPYGEN_DISABLE_setXmlFileName_KRTaFileString_KRTaFileString_KRTaFileString
    void setXmlFileName(const dstoute::aFileString& documentName, const dstoute::aFileString& perturbationDocumentName, const dstoute::aFileString& keyFileName) override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_setXmlFileName_KRTaFileString_KRTaFileString_KRTaFileString;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "setXmlFileName", documentName, perturbationDocumentName, keyFileName);
        return CxxCallBase::setXmlFileName(documentName, perturbationDocumentName, keyFileName);
    }
#endif

#ifndef RPYGEN_DISABLE_setXmlFileBuffer_Ph_KRTsize_t
    void setXmlFileBuffer(unsigned char* documentBuffer, const size_t& documentBufferSize) override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_setXmlFileBuffer_Ph_KRTsize_t;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "setXmlFileBuffer", documentBuffer, documentBufferSize);
        return CxxCallBase::setXmlFileBuffer(documentBuffer, documentBufferSize);
    }
#endif

#ifndef RPYGEN_DISABLE_exportToFile_KRTaFileString
    size_t exportToFile(const dstoute::aFileString& dataFileName) override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_exportToFile_KRTaFileString;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(size_t), LookupBase,
            "exportToFile", dataFileName);
        return CxxCallBase::exportToFile(dataFileName);
    }
#endif

#ifndef RPYGEN_DISABLE_exportToBuffer_RTostringstream
    size_t exportToBuffer(std::ostringstream& documentBuffer) override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_exportToBuffer_RTostringstream;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(size_t), LookupBase,
            "exportToBuffer", documentBuffer);
        return CxxCallBase::exportToBuffer(documentBuffer);
    }
#endif

#ifndef RPYGEN_DISABLE_exportToBuffer_RPh
    size_t exportToBuffer(unsigned char&* documentBuffer) override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_exportToBuffer_RPh;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(size_t), LookupBase,
            "exportToBuffer", documentBuffer);
        return CxxCallBase::exportToBuffer(documentBuffer);
    }
#endif

#ifndef RPYGEN_DISABLE_exportToDocumentObjectModel_KRTaString
    void exportToDocumentObjectModel(const dstoute::aString& documentType) override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_exportToDocumentObjectModel_KRTaString;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "_exportToDocumentObjectModel", documentType);
        return CxxCallBase::exportToDocumentObjectModel(documentType);
    }
#endif

#ifndef RPYGEN_DISABLE_parseDOM_v
    void parseDOM() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_parseDOM_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "_parseDOM", );
        return CxxCallBase::parseDOM();
    }
#endif

#ifndef RPYGEN_DISABLE_initialiseDependencies_v
    void initialiseDependencies() override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_initialiseDependencies_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(void), LookupBase,
            "_initialiseDependencies", );
        return CxxCallBase::initialiseDependencies();
    }
#endif


#ifndef RPYBLD_DISABLE_getLinearInterpolation_RTFunction_KRTvector_double_
  #ifndef RPYBLD_UDISABLE_janus__Janus_getLinearInterpolation
    using janus::Janus::getLinearInterpolation;
    #define RPYBLD_UDISABLE_janus__Janus_getLinearInterpolation
  #endif
#endif
#ifndef RPYBLD_DISABLE_getLinearInterpolation_RTFunction
  #ifndef RPYBLD_UDISABLE_janus__Janus_getLinearInterpolation
    using janus::Janus::getLinearInterpolation;
    #define RPYBLD_UDISABLE_janus__Janus_getLinearInterpolation
  #endif
#endif
#ifndef RPYBLD_DISABLE_getPolyInterpolation_RTFunction_KRTvector_double_
  #ifndef RPYBLD_UDISABLE_janus__Janus_getPolyInterpolation
    using janus::Janus::getPolyInterpolation;
    #define RPYBLD_UDISABLE_janus__Janus_getPolyInterpolation
  #endif
#endif
#ifndef RPYBLD_DISABLE_getPolyInterpolation_RTFunction
  #ifndef RPYBLD_UDISABLE_janus__Janus_getPolyInterpolation
    using janus::Janus::getPolyInterpolation;
    #define RPYBLD_UDISABLE_janus__Janus_getPolyInterpolation
  #endif
#endif
#ifndef RPYBLD_DISABLE_getUngriddedInterpolation_RTFunction_KRTvector_double_
  #ifndef RPYBLD_UDISABLE_janus__Janus_getUngriddedInterpolation
    using janus::Janus::getUngriddedInterpolation;
    #define RPYBLD_UDISABLE_janus__Janus_getUngriddedInterpolation
  #endif
#endif
#ifndef RPYBLD_DISABLE_getUngriddedInterpolation_RTFunction
  #ifndef RPYBLD_UDISABLE_janus__Janus_getUngriddedInterpolation
    using janus::Janus::getUngriddedInterpolation;
    #define RPYBLD_UDISABLE_janus__Janus_getUngriddedInterpolation
  #endif
#endif
#ifndef RPYBLD_DISABLE_getAllDescendents_Tsize_t_b
  #ifndef RPYBLD_UDISABLE_janus__Janus_getAllDescendents
    using janus::Janus::getAllDescendents;
    #define RPYBLD_UDISABLE_janus__Janus_getAllDescendents
  #endif
#endif
#ifndef RPYBLD_DISABLE_getAllAncestors_Tsize_t
  #ifndef RPYBLD_UDISABLE_janus__Janus_getAllAncestors
    using janus::Janus::getAllAncestors;
    #define RPYBLD_UDISABLE_janus__Janus_getAllAncestors
  #endif
#endif
#ifndef RPYBLD_DISABLE_getIndependentAncestors_Tsize_t
  #ifndef RPYBLD_UDISABLE_janus__Janus_getIndependentAncestors
    using janus::Janus::getIndependentAncestors;
    #define RPYBLD_UDISABLE_janus__Janus_getIndependentAncestors
  #endif
#endif
#ifndef RPYBLD_DISABLE_getPdfFromAntecedents_Tsize_t
  #ifndef RPYBLD_UDISABLE_janus__Janus_getPdfFromAntecedents
    using janus::Janus::getPdfFromAntecedents;
    #define RPYBLD_UDISABLE_janus__Janus_getPdfFromAntecedents
  #endif
#endif
#ifndef RPYBLD_DISABLE_isJanusInitialised_b
  #ifndef RPYBLD_UDISABLE_janus__Janus_isJanusInitialised
    using janus::Janus::isJanusInitialised;
    #define RPYBLD_UDISABLE_janus__Janus_isJanusInitialised
  #endif
#endif
#ifndef RPYBLD_DISABLE_retrieveProvenanceReference_KRTaString_Tsize_t
  #ifndef RPYBLD_UDISABLE_janus__Janus_retrieveProvenanceReference
    using janus::Janus::retrieveProvenanceReference;
    #define RPYBLD_UDISABLE_janus__Janus_retrieveProvenanceReference
  #endif
#endif
#ifndef RPYBLD_DISABLE_KwriteDocumentObjectModel_KRTaFileString
  #ifndef RPYBLD_UDISABLE_janus__Janus_writeDocumentObjectModel
    using janus::Janus::writeDocumentObjectModel;
    #define RPYBLD_UDISABLE_janus__Janus_writeDocumentObjectModel
  #endif
#endif
#ifndef RPYBLD_DISABLE_KwriteDocumentObjectModel_RTostringstream
  #ifndef RPYBLD_UDISABLE_janus__Janus_writeDocumentObjectModel
    using janus::Janus::writeDocumentObjectModel;
    #define RPYBLD_UDISABLE_janus__Janus_writeDocumentObjectModel
  #endif
#endif
#ifndef RPYBLD_DISABLE_releaseJanusDomParser_v
  #ifndef RPYBLD_UDISABLE_janus__Janus_releaseJanusDomParser
    using janus::Janus::releaseJanusDomParser;
    #define RPYBLD_UDISABLE_janus__Janus_releaseJanusDomParser
  #endif
#endif
#ifndef RPYBLD_DISABLE_deleteLuaState_v
  #ifndef RPYBLD_UDISABLE_janus__Janus_deleteLuaState
    using janus::Janus::deleteLuaState;
    #define RPYBLD_UDISABLE_janus__Janus_deleteLuaState
  #endif
#endif

    using janus::Janus::document_;
    using janus::Janus::documentCreated_;
    using janus::Janus::dataFileName_;
    using janus::Janus::keyFileName_;
    using janus::Janus::documentType_;
    using janus::Janus::isJanusInitialised_;
    using janus::Janus::fileHeader_;
    using janus::Janus::variableDef_;
    using janus::Janus::propertyDef_;
    using janus::Janus::breakpointDef_;
    using janus::Janus::griddedTableDef_;
    using janus::Janus::ungriddedTableDef_;
    using janus::Janus::function_;
    using janus::Janus::signalDef_;
    using janus::Janus::checkData_;
    using janus::Janus::hasCheckData_;
    using janus::Janus::isCheckDataCurrent_;
    using janus::Janus::perturbationsFileName_;
    using janus::Janus::outputIndex_;
    using janus::Janus::nbp_;
    using janus::Janus::frac_;
    using janus::Janus::bpa_;
    using janus::Janus::bpi_;
    using janus::Janus::nOrd_;
    using janus::Janus::fracBp_;
    using janus::Janus::doMathML_to_ExprTk_;
    using janus::Janus::kState_;

};

}; // namespace rpygen
